### ISSUE TITLE
Используйте <stdio.h>

### ISSUE THREAD

**Issue by oleg-tgn** [AlexZaurovna/OAiP_Labs_Kyabisheva#1]
Используйте <stdio.h> для работы с консолью

**Comment by AlexZaurovna** [comment]
Здравствуйте. Скажите, пожалуйста, нужно ли делать отчёт со скриншотами по первой лабораторной, и  обязательно ли использовать Visual Studio?

**Comment by oleg-tgn** [comment]
Здравствуйте, 
1) Нет скриншоты, не обязательно. Достаточно примеров входных и выходных данных просто в виде текста. 
2) Вижуал студия не обязательно использовать дома. Но
- Вы должны быть готовы продемонстрировать работу вашего приложения в аудитории, там установлена VS2015.
- Вы должны уметь работать в VS, она будет у вас при сдача экзамена

**Comment by AlexZaurovna** [comment]
Хорошо. Большое спасибо
