### ISSUE TITLE
Удалите неиспользуемые заголовочные файлы

### ISSUE THREAD

**Issue by oleg-tgn** [AlexZaurovna/OAiP_Labs_Kyabisheva#2]
Все ли эти заголовочные файлы необходимы в программе?

#include <conio.h>
#include <stdio.h> 
#include <iostream> 
#include <Windows.h>

**Comment by oleg-tgn** [comment]
Все ли эти заголовочные файлы необходимы?

**Comment by oleg-tgn** [comment]
#include <conio.h>
#include <stdio.h> 
#include <iostream> 
#include <Windows.h> 
using namespace std;

**Comment by AlexZaurovna** [comment]
Ненужные заголовочные файлы удалены
