### ISSUE TITLE
Разберитесь с кодировкой файла

### ISSUE THREAD

**Issue by oleg-tgn** [AlexZaurovna/OAiP_Labs_Kyabisheva#3]
Разберитесь с кодировкой файла, чтобы комментарии читались в гите

**Comment by AlexZaurovna** [comment]
Здравствуйте. У меня комментарии открываются на русском языке в нормальном виде и на компьютере, и на телефоне. Что я делаю не так?

**Comment by oleg-tgn** [comment]
Да, все ок сейчас
