### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by oleg-tgn** [AlexZaurovna/OAiP_Labs_Kyabisheva#8]
1) Зачем папка в папке? Пусть проекты лежат в корне репозитория

2) В проектах не должно быть [Debug и прочего](https://github.com/oleg-tgn/for-students/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-Git)

3) [Именования файлов](https://github.com/oleg-tgn/for-students/wiki/%D0%98%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

4) Опять проблемы с кодировкой, решайте их 
`printf("Ââåäèòå ðàçìåð ìàñèâà ");`

5) [Оформление кода](https://github.com/oleg-tgn/for-students/wiki/%D0%9E%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%B4%D0%B0)

6) Нужен пробел, чтобы лучше читалось
неправильно
`#include<stdio.h>`
правильно
`#include <stdio.h>`

7) `fncshn` - что за набор букв?
См. Именования

8) Проверки на корректность ввода вынесли в отдельную функцию, а почему тут это
```
while (!(sz > 0)) {
		fncshn(&sz);
	}
```

9) `sz` - это разве переменная, которая своим названием нам что-то говорит

10) Вот это все как-то очень сложно написано. Надо найти способ упростить
```
for (int i = 0; i < sz; i++) {
		if(abs(array[i])<=3){
			printf("%d ", array[i]);
		}
		else {
			for (int j = 2; j < array[i]; j++) {
				if (array[i] % j == 0) {
					break;
				}
				if (j == array[i] - 1) {
					printf("%d ", array[i]);
				}
			}
		}
	}
```

11) 
```
int nmbr;
		while (!scanf("%d", &nmbr)) {
			printf("Îøèáêà ââîäà. Ïîâòîðèòå ïîïûòêó ");
			while (getchar() != '\n');
		}
```
Откуда лишняя табуляция?

12) `nmbr` - чт з м тк?
почему не написать полностью `number`?

**Comment by AlexZaurovna** [comment]
Исправлены пункты 1-7, 9, 11, 12. Удалена часть кода, указанная в пункте 8.
